# Generated by Django 5.2.11 on 2026-02-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_remove_team_members_team_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="teams",
        ),
        migrations.AddField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="manager.team"
            ),
        ),
    ]
