# Generated by Django 5.2.11 on 2026-02-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_remove_project_teams_project_teams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "Member"},
        ),
    ]
